language: java
jdk:
- openjdk6
before_install:
- python travis.py;
install:
- mvn install -DskipTests=true
env:
  global:
  - SONATYPE_USERNAME=deployment
  - secure: bIZ7vavx7vDd+9nFRyvvhRRQbMOOuMy1BLnLMWUsdG+XTF6ge6aS0J4Mxw7Ptddayfh2pQJvg9c7oSUAIFkG5at3AzLpsyIEgVykVD4mwB2i07NdyEO/1THeIFZJDMCto5rHinpC5fERIP2UzOS485suiLRKHZSuiFz7YVD2f1Y=
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { mvn deploy -DskipTests=true; };'
- '[[ $TRAVIS_BRANCH == "develop" ]] && { mvn deploy -DskipTests=true; };'
