language: java
jdk:
- openjdk6
before_install:
- python travis.py --mirrors;
install:
- mvn install -DskipTests=true
env:
  global:
  - SONATYPE_USERNAME=deployment
  - secure: Jj+p5gZLtuvzWoAC3HWYPESFFjletKwPS9Xoo5+ADb0IlB6hcs6smj2hddC/AUqkQ/2i4rgTOUUouX0LM9nWyNkhJ3AgIBPdnC1pbI08X1J8TxP02FD/qmqPtLBFpIQJLHrF5OftfGPqkbGehQ9NUa4LmZoLj9eFfQX59gj6V6E=
after_success:
- '[[ $TRAVIS_REPO_SLUG == telefonicaid* ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] && { python travis.py --deploy; mvn deploy -DskipTests=true; };'
- '[[ $TRAVIS_REPO_SLUG == telefonicaid* ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "develop" ]] && { python travis.py --deploy; mvn deploy -DskipTests=true; };'
